### ISSUE TITLE
Unable to mount on 10.7 Lion

### ISSUE THREAD

**Issue by davidwinter** [devstructure/ubuntu#4]
When running `./build-iso` on Mac OS X Lion 10.7, I get the following error:

```
./build-iso 
hdiutil: attach failed - no mountable file systems
Password:
mount: You must specify a filesystem type with -t.
```

This is with the `ubuntu-11.10-server-i386.iso` image.

**Comment by yep** [comment]
hi,
i think i fixed this issue and created a [pull request](https://github.com/devstructure/ubuntu/pull/5) for it.

**Comment by PopularUbuntu** [comment]
Please elaborate more.
